[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development", "rendering", "graphics"]
description = "2d sdf shape renderer plugin for Bevy"
edition = "2021"
keywords = ["gamedev", "bevy", "sdf"]
license = "MIT OR Apache-2.0"
name = "bevy_smud"
repository = "https://github.com/johanhelsing/bevy_smud"
version = "0.4.0"

[dependencies]
bevy = {version = "0.10", default-features = false, features = [
  "bevy_core_pipeline",
  "bevy_render",
  "bevy_asset", # needed for handle ids
]}
bytemuck = { version = "1.7", features = ["derive"] }
copyless = "0.1"
bitflags = "1.3"

[dev-dependencies]
bevy = {version = "0.10", default-features = false, features = [
  "bevy_winit",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
  "filesystem_watcher",
]}
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "bevy_main" }
bevy_lospec = "0.4"
bevy_pancam = {git = "https://github.com/johanhelsing/bevy_pancam", branch = "bevy-0.10"}
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[patch."https://github.com/bevyengine/bevy"]
bevy = "0.10"
