[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development", "rendering", "graphics"]
description = "2d sdf shape renderer plugin for Bevy"
edition = "2021"
keywords = ["gamedev", "bevy", "sdf"]
license = "MIT OR Apache-2.0"
name = "bevy_smud"
repository = "https://github.com/johanhelsing/bevy_smud"
version = "0.4.0"

[dependencies]
bevy = {version = "0.9", default-features = false, features = ["render", "bevy_asset"]}
bytemuck = "1.7"
copyless = "0.1"

[dev-dependencies]
bevy = {version = "0.9", default-features = false, features = [
  "render",
  "bevy_winit",
  "x11", # github actions runenrs don't have libxkbcommon installed, so can't use wayland
  "filesystem_watcher",
]}
bevy_asset_loader = "0.14"
bevy_lospec = "0.3"
bevy_pancam = "0.7"
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
